#pragma once

struct FeatureIndex
{
    enum enumFeatures
    {
        FEATURE_NONE = 0,

        FEATURE_CHEST_A_CLOSED = 1,
        FEATURE_CHEST_B_CLOSED = 2,
        FEATURE_CHEST_C_CLOSED = 3,

        FEATURE_CHEST_A_OPEN = 4,
        FEATURE_CHEST_B_OPEN = 5,
        FEATURE_CHEST_C_OPEN = 6,
    };
    static const int MARKER_FEATURE_CHEST_CLOSED_BEGIN = FEATURE_CHEST_A_CLOSED;
    static const int MARKER_FEATURE_CHEST_CLOSED_END = FEATURE_CHEST_C_CLOSED;
    static const int MARKER_FEATURE_CHEST_OPEN_BEGIN = FEATURE_CHEST_A_OPEN;
    static const int MARKER_FEATURE_CHEST_OPEN_END = FEATURE_CHEST_C_OPEN;
    static const int NUM_FEATURE_TYPES = MARKER_FEATURE_CHEST_OPEN_END + 1;

    enum enumBlueprintFeatures
    {
        BLUEPRINT_FEATURE_NONE = 0x00,

        BLUEPRINT_FEATURE_CHEST_A_CLOSED = 0x01,
        BLUEPRINT_FEATURE_CHEST_B_CLOSED = 0x02,
        BLUEPRINT_FEATURE_CHEST_C_CLOSED = 0x03,

        BLUEPRINT_FEATURE_CHEST_A_OPEN = 0x04,
        BLUEPRINT_FEATURE_CHEST_B_OPEN = 0x05,
        BLUEPRINT_FEATURE_CHEST_C_OPEN = 0x06
    };
    //static const int MARKER_BLUEPRINT_FEATURE_CHEST_CLOSED_BEGIN = BLUEPRINT_FEATURE_CHEST_A_CLOSED;
    //static const int MARKER_BLUEPRINT_FEATURE_CHEST_CLOSED_END = BLUEPRINT_FEATURE_CHEST_C_CLOSED;
    //static const int MARKER_BLUEPRINT_FEATURE_CHEST_OPEN_BEGIN = BLUEPRINT_FEATURE_CHEST_A_OPEN;
    //static const int MARKER_BLUEPRINT_FEATURE_CHEST_OPEN_END = BLUEPRINT_FEATURE_CHEST_C_OPEN;
    static const int NUM_BLUEPRINT_FEATURE_TYPES = NUM_FEATURE_TYPES; // For the time being, assuming 1:1 between blueprints and features.
};